# Generated by Django 4.0.10 on 2023-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='1kg', max_length=500),
        ),
    ]
