# Generated by Django 4.0.10 on 2023-10-10 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_order', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='2kg', max_length=500),
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=12)),
                ('price', models.CharField(default=0, max_length=100)),
                ('number_product', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2023, 10, 10))),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_order.product')),
            ],
        ),
    ]
