# Generated by Django 4.0.10 on 2023-10-10 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_order', '0003_alter_product_quantity_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2023, 10, 10)),
        ),
    ]
