# Generated by Django 4.0.10 on 2023-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_order', '0004_alter_order_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='name',
            field=models.CharField(default='Biswajit Ghosh', max_length=100),
        ),
    ]
