# Generated by Django 4.0.10 on 2023-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_order', '0006_alter_order_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
